### ISSUE TITLE
Support Atlassian Confluence Cloud

### ISSUE THREAD

**Issue by Compy** [GerevAI/gerev#28]
# Issue
Currently only self-hosted Atlassian Confluence is supported. However Atlassian Cloud is widely adopted and has a nearly identical API endpoint structure.

Currently Gerev suggests creating a PAT in order for the system to authenticate and pull data. That PAT is then used as a bearer token to the upstream Atlassian API. For Cloud installations, account-specific API tokens are allowed, which are used as basic auth where the username is the account holder's email address, and the password is the generated API key.

From there, the same endpoint structure and payloads are used to scrape the `/space` endpoint

API Tokens are managed [here](https://id.atlassian.com/manage-profile/security/api-tokens)

## Further Questions
How do we distinguish auth types? It doesn't make sense to duplicate the entire data source logic just to support a different auth scheme.

**Comment by bryan-pakulski** [comment]
Opened a pull request, created a solution locally to connect to my company confluence cloud;

https://github.com/GerevAI/gerev/pull/38

**Comment by Roey7** [comment]
Solved, thanks @bryan-pakulski
