### ISSUE TITLE
What does the main repo image text mean?

### ISSUE THREAD

**Issue by gene1wood** [GerevAI/gerev#33]
The main repo image

![everything](https://raw.githubusercontent.com/GerevAI/gerev/main/images/everything.png)

says

> Steve Job* searches with gerev.ai
> *similarly named to someone famous, we paid him to do so

I get from the tone that this is mean to be a joke of some kind but I don't get it. I'm a native English speaker and this goes over my head.

* Is the idea that that name of the AI is "Steve Job" (like Siri or Dall-E) and it's a play on "Steve Jobs"?
* Is the idea that Steve Jobs likes this tool so much he's using it from beyond the grave?
* Is the joke that you paid a dead person (which isn't possible)?

I only mention it as you may want to modify this image to something that more people understand. Also, it's a little icky to be making a joke about a dead guy using your product, if indeed that is the joke.

**Comment by yuvalsteuer** [comment]
Hi boomer, Are you asking of us to explain a joke? 

Switched it up a bit.

**Comment by gene1wood** [comment]
Hehe sorry, I didn't mean explain the joke to me. I just meant, as one data point, of someone not getting it, maybe others also didn't get it.

Anyhow, sorry, I didn't mean it as a critique or complaint, I was just trying to help make gerev more accessible.

**Comment by yuvalsteuer** [comment]
Haha thanks for pointing it out!
