### ISSUE TITLE
Add UI functionality to delete data sources

### ISSUE THREAD

**Issue by Roey7** [GerevAI/gerev#34]
Add a pencil icon on top right of Data Source Screen, on click, it should turn on edit mode.
On edit mode, connected data sources should have a " - " button instead of a " + ".
When hovering the "minus" button on a connected data source on edit mode, it should be red or something.
On click, call a function that makes an "axios.post" to delete integration with its name.
In backend, add an empty endpoint that just returns 200 OK.
Show a toast on success.

**Comment by NathanCrotty** [comment]
I think I can handle this.

**Comment by NathanCrotty** [comment]
[Pull request for this issue](https://github.com/GerevAI/gerev/pull/62#issue-1641147591)
