### ISSUE TITLE
UI for adding CA certificates

### ISSUE THREAD

**Issue by aSilentSniper** [GerevAI/gerev#43]
I think there should be a way to add a ca certificate to the container or at leas an option to disable cert checks. Can't add my bookstack instance because of cert errors

**Comment by yuvalsteuer** [comment]
Could you send the errors here on DM them on discord?

**Comment by aSilentSniper** [comment]
i am on the error with Roey i just thougt it would be more convenient to have an ui option to handle the scenario to either disable ssl checks or to add the ca cert

**Comment by Roey7** [comment]
Disabled ssl checks for now
